@api = http://localhost:5000/api/v1

GET {{api}}/orders/2277265d-b37a-4535-bfee-9e408c34af09
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImRkMGQ1Mjg1LWQxMTYtNGEyZS1hNjJhLTVlOWM2Y2NmMDcyYyJ9.9Z2hJ4KfnchXG5x8tXRtlhwOGQD9EYTRKpjdS_OtnTk

###
GET {{api}}/orders/95bc4589-a1a5-4ab4-8f6d-57b39460a8ae,c9e8a8ce-11d6-4671-9919-caba0fe01ea6,d4dc9fc4-3c30-4c7a-862c-9ce90aa7797f
x-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImRkMGQ1Mjg1LWQxMTYtNGEyZS1hNjJhLTVlOWM2Y2NmMDcyYyJ9.9Z2hJ4KfnchXG5x8tXRtlhwOGQD9EYTRKpjdS_OtnTk

